openapi: 3.0.3
info:
  title: PGW Auth Service
  description: |
    The primary function of this service is to authenticate merchants.
  version: 1.0.0
  contact:
    name: Gustavo Ferreira
    email: gustavojcoferreira@gmail.com
servers:
- url: http://localhost:{port}{basePath}
  description: Local development
  variables:
    port:
      default: '8080'
      enum:
      - '8080'
    basePath:
      default: '/api/v1'
      enum:
      - '/api/v1'
tags:
- name: maintenance
  description: Service maintenance operations
- name: auth
  description: Auth validation operations
paths:
  /healthcheck:
    get:
      tags:
      - maintenance
      summary: Check API service health
      description: Returns status of the API service.
      responses:
        '200':
          description: Service is OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckResponse'
        '500':
          $ref: '#/components/responses/InternalError'
  /auth:
    post:
      tags:
      - auth
      summary: Validate merchant credentials
      description: This endpoint validates whether the merchant's credentials are valid or not.
      requestBody:
        description: merchant credentials
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: |
            This API returns 200 for both valid and invalid credentials. The body of the response will
            report whether the credentials were valid or not.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  responses:
    BadRequest:
      description: Invalid Parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
  schemas:
    HealthcheckResponse:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          enum:
          - OK
    ApiErrorResponse:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: Message explaining the error reason.
    Credentials:
      type: object
      required:
      - username
      - password
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      required:
      - valid
      properties:
        valid:
          type: boolean